# Generated by Django 4.0.2 on 2022-03-03 06:12

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_alter_bid_listing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='bidder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bid',
            name='listing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='auctions.listing'),
        ),
        migrations.AlterField(
            model_name='bid',
            name='value',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.99)]),
        ),
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('Miscs', 'Miscs'), ('Vehicules', 'Vehicules'), ('Home', 'Home'), ('Electronics', 'Electronics'), ('Clothes', 'Clothes'), ('Toys', 'Toys')], default='Miscs', max_length=64),
        ),
    ]
