# Generated by Django 4.0.2 on 2022-03-04 14:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_listing_watchlisted_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='watchlisted_by',
            field=models.ManyToManyField(blank=True, related_name='watchlist', to=settings.AUTH_USER_MODEL),
        ),
    ]
