# Generated by Django 4.0.2 on 2022-03-04 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_alter_listing_watchlisted_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='watchlisted_by',
            new_name='watchlisting_users',
        ),
    ]
