# Generated by Django 4.0.2 on 2022-03-05 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_listing_closed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('Miscs', 'Miscs'), ('Vehicules', 'Vehicules'), ('Home', 'Home'), ('Electronics', 'Electronics'), ('Fashion', 'Fashion'), ('Toys', 'Toys'), ('Video Games', 'Video Games'), ('Cooking', 'Cooking'), ('Study', 'Study')], default='Miscs', max_length=64),
        ),
    ]
